version: '3'
networks:
  internal:
    driver: bridge
services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - 80:80
    networks:
      - internal
  
  yellowapp:
    container_name: yellowapp
    build:
      context: ./yellow_app
      dockerfile: Dockerfile
    networks:
      - internal
  
  greenapp:
    container_name: greenapp
    build:
      context: ./green_app
      dockerfile: Dockerfile
    networks:
      - internal
  flaskapp:
    container_name: flaskapp
    build:
      context: ./python_app
      dockerfile: Dockerfile
    networks:
      - internal
  
